name: iOS-CI-Test

on:
    push:
        branches:
        - dataService

jobs:
    installPods:
        name: Installing Dependencies
        runs-on: macos-latest
        steps:
            - name: Cache Pods dependencies
              uses: actions/cache@v2
              with:
                path: Pods
                key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
                restore-keys: |
                    ${{ runner.os }}-pods-
            - name: Install pod dependencies
              run: pod install
              shell: bash

    test:
        needs: installPods
        name: Test
        runs-on: macos-latest
        strategy:
            matrix:
                destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 11']
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                ref: ${{ github.ref }}
            - name: Build
              run: |
                pod install --repo-update --clean-install
                xcodebuild clean build -project TabBarCoordinatorApp.xcodeproj -scheme TabBarCoordinatorApp -destination "platform=iOS Simulator,OS=14.4,name=iPhone 11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
              env:
                destination:: ${{ matrix.destination }}
            - name: Test
              run: |
                xcodebuild clean test -project TabBarCoordinatorApp.xcodeproj -scheme TabBarCoordinatorApp -destination "platform=iOS Simulator,OS=14.4,name=iPhone 11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
              env:
                destination: ${{ matrix.destination }}
